### ISSUE TITLE
Support for ZoomGov

### ISSUE THREAD

**Issue by petersonjdNIH** [davidshumway/zoomie#9]
ZoomGov is similar to Zoom in a lot of ways, but uses different infrastructure, URLs, etc. I suspect this is causing the Zoomie plug-in to be unaware and not load to work like it does with the original Zoom.

Anything that can be done to resolve this would be most appreciated.

<img width="756" alt="Screenshot 2023-12-14 at 8 37 34 AM" src="https://github.com/davidshumway/zoomie/assets/54716797/2365fef2-6ac1-439f-bf3a-8f8bf9a3209c">

**Comment by davidshumway** [comment]
Interesting! I don't have a zoomgov.com account, but it'd be interesting to see try the extension there.

**Comment by davidshumway** [comment]
> ZoomGov is similar to Zoom in a lot of ways, but uses different infrastructure, URLs, etc. I suspect this is causing the Zoomie plug-in to be unaware and not load to work like it does with the original Zoom.

The extension runs when the URL matches the pattern:
```
https://zoom.us/wc/*
https://*.zoom.us/wc/*
```

There are few URL patterns for the web client, but mostly they end up at the same place, i.e. the zoom room. Rather than finding out all of the possible URLs, the extension matches on any pattern including "/wc/". A notable exception to a "/wc/" URL that doesn't lead to a zoom room is https://*.zoom.us/wc/home, which is apparently similar to the home page that's visible in the regular desktop client. In any case, the extension simply polls every 5 times per second for the breakout room button to appear, then adds functionality from there.

**Comment by davidshumway** [comment]
I added https://*.zoomgov.com/wc/* to the list of allowed URLs and updated the extension on the Mozilla add-ons store, so you can give it a shot. If there aren't any layout differences in the web client, then it should work as expected.

**Comment by petersonjdNIH** [comment]
Awesome. You're a legend. I'll start testing and see how it goes.

**Comment by petersonjdNIH** [comment]
Seems to be working fine:
<img width="754" alt="Screenshot 2023-12-15 at 11 30 55 AM" src="https://github.com/davidshumway/zoomie/assets/54716797/597ae701-f965-447c-9c0f-e30f2b45e79f">
